### ISSUE TITLE
TypeError: unsupported type for timedelta seconds component: NoneType

### ISSUE THREAD

**Issue by ladiko** [Minege/eSSP#10]
I always get this when calling sync()

```
Traceback (most recent call last):
  File "./cc_ssp.py", line 11, in <module>
    k.sync()
  File "/home/user/eSSP.py", line 289, in sync
    result = self.send([self.getseq(), '0x1', '0x11'])
  File "/home/user/eSSP.py", line 402, in send
    response = self.read(process)
  File "/home/user/eSSP.py", line 410, in read
    timeout_expired = datetime.datetime.now() + datetime.timedelta(seconds=self.timeout)
TypeError: unsupported type for timedelta seconds component: NoneType
```

**Comment by Minege** [comment]
Please include your OS informations and your Python version that you use to run our program.

**Comment by ladiko** [comment]
```
ladiko@machine:~$ python --version
Python 2.7.6
ladiko@machine:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

**Comment by Minege** [comment]
Can you try to install it like this `pip install git+https://github.com/Minege/eSSP` ?
It looks like you are using an older version of the library

**Comment by Minege** [comment]
datetime is not used in the repo, closing the issue. It should work if you install it directly from the github repository
